workflows:
ios-workflow:
  name: Build Iron Calculator iOS App
  max_build_duration: 60
  instance_type: mac_mini_m2
  environment:
    node: "18"
    groups:
      - secrets-group  # أي متغيرات سرية
  scripts:
    - name: Install Dependencies
      script: |
        npm install
    - name: Build Project
      script: |
        npm run build
    - name: Capacitor Init and Sync
      script: |
        npx cap init "IronCalculator" "com.bina.yemen" --web-dir=.
        npx cap sync ios
    - name: Use Environment Variables
      script: |
        echo "API Key is $API_KEY"
        echo "Server URL is $SERVER_URL"
  artifacts:
    - build/**