workflows:
ios-workflow:
  name: Build Iron Calculator iOS App
  max_build_duration: 30
  instance_type: mac_mini_m2
  environment:
    node: "18"
  scripts:
    - name: Install Dependencies
      script: npm install
    - name: Build Project
      script: npm run build
    - name: Capacitor Sync iOS
      script: |
        npx cap init "IronCalculator" "com.bina.yemen" --web-dir=.
        npx cap sync ios