workflows:
ios-workflow:
  name: Build Iron Calculator iOS App
  max_build_duration: 60
  instance_type: mac_mini_m2
  environment:
    node: 18
    vars:
      APP_NAME: "Iron Calculator"
  scripts:
    - name: Install dependencies
      script: |
        npm install
    - name: Build project
      script: |
        npm run build
        npx cap sync ios
  artifacts:
    - build/**